export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const ADD_STORE_ITEMS = 'ADD_STORE_ITEMS';
export const SET_IN_CART_INDICATOR = "SET_IN_CART_INDICATOR";
export const REMOVE_IN_CART_INDICATOR = "REMOVE_IN_CART_INDICATOR";